name: A11y Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run contrast utility tests
      run: npm run test:run
    
    - name: Run test coverage
      run: npm run test:coverage
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  a11y-check:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build project
      run: npm run build
    
    - name: Start test server
      run: |
        npm run serve &
        sleep 5
    
    - name: Run axe-core accessibility tests
      run: |
        npm install -g @axe-core/cli
        axe http://localhost:3000 --exit
    
    - name: Run contrast validation
      run: node -e "
        const { runA11yQA } = require('./dist/a11y/a11y-qa.js');
        const result = runA11yQA();
        if (!result.overallPass) {
          console.error('A11y QA failed:', result.violations);
          process.exit(1);
        }
        console.log('A11y QA passed');
      "

  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Run security audit
      run: npm audit --audit-level=moderate
    
    - name: Run dependency check
      run: npm outdated
